/**
 * Privacy Policy Page
 */
import React from 'react';
import { motion } from 'framer-motion';
import { Shield, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const PrivacyPolicyPage: React.FC = () => {
  const navigate = useNavigate();
  const lastUpdated = 'March 20, 2026';

  return (
    <div className="container mx-auto px-6 max-w-4xl py-10">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        {/* Header */}
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-slate-400 hover:text-white mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 bg-violet-500/20 rounded-xl flex items-center justify-center">
            <Shield className="w-5 h-5 text-violet-400" />
          </div>
          <h1 className="text-3xl font-bold text-white">Privacy Policy</h1>
        </div>
        <p className="text-slate-400 mb-10">Last updated: {lastUpdated}</p>

        {/* Content */}
        <div className="prose prose-invert max-w-none space-y-8">
          <Section title="1. Introduction">
            <p>BodyScan AI ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application and website (collectively, the "Service").</p>
            <p>By using the Service, you agree to the collection and use of information in accordance with this policy.</p>
          </Section>

          <Section title="2. Information We Collect">
            <h4 className="text-white font-semibold mt-4">2.1 Personal Information</h4>
            <ul>
              <li>Full name and email address (when you create an account)</li>
              <li>Phone number (optional, for WhatsApp notifications)</li>
              <li>Payment information (processed securely through Razorpay; we do not store card details)</li>
            </ul>
            <h4 className="text-white font-semibold mt-4">2.2 Body Measurement Data</h4>
            <ul>
              <li>Photos uploaded for body scanning (processed in real-time and not permanently stored on our servers)</li>
              <li>Body measurements derived from AI analysis</li>
              <li>Size recommendations and fit analysis results</li>
            </ul>
            <h4 className="text-white font-semibold mt-4">2.3 Usage Data</h4>
            <ul>
              <li>Device type, operating system, and browser information</li>
              <li>App usage patterns and feature interactions</li>
              <li>IP address and approximate location</li>
            </ul>
          </Section>

          <Section title="3. How We Use Your Information">
            <ul>
              <li>To provide and maintain our AI body scanning service</li>
              <li>To generate body measurements and size recommendations</li>
              <li>To process payments and manage subscriptions</li>
              <li>To send notifications about your account and service updates</li>
              <li>To improve our AI models and service accuracy</li>
              <li>To respond to your support requests</li>
            </ul>
          </Section>

          <Section title="4. AI & Image Processing Disclosure">
            <p>Our Service uses artificial intelligence to analyze body images for measurements. Important details:</p>
            <ul>
              <li><strong>Image Processing:</strong> Uploaded photos are processed in real-time using AI models (PARE, SMPL-Anthropometry) and are not permanently stored on our servers after processing.</li>
              <li><strong>AI Accuracy:</strong> Measurements are estimates generated by machine learning models and may not be 100% accurate. They should not be used for medical purposes.</li>
              <li><strong>Data Retention:</strong> Derived measurement data (not images) is stored in your account for your reference and can be deleted at any time.</li>
            </ul>
          </Section>

          <Section title="5. Data Sharing & Third Parties">
            <p>We do not sell your personal information. We share data only with:</p>
            <ul>
              <li><strong>Razorpay:</strong> For payment processing (subject to <a href="https://razorpay.com/privacy/" target="_blank" rel="noopener noreferrer" className="text-accent-400 hover:text-accent-300">Razorpay's Privacy Policy</a>)</li>
              <li><strong>Google:</strong> For Google Sign-In authentication</li>
              <li><strong>WhatsApp Business API:</strong> For payment receipts (only if you provide your phone number)</li>
            </ul>
          </Section>

          <Section title="6. Data Security">
            <p>We implement industry-standard measures to protect your data:</p>
            <ul>
              <li>Passwords are hashed using Argon2 (industry gold standard)</li>
              <li>All API communications use HTTPS encryption</li>
              <li>JWT tokens with expiry for session management</li>
              <li>Rate limiting to prevent abuse</li>
            </ul>
          </Section>

          <Section title="7. Your Rights">
            <p>Under applicable data protection laws (including India's DPDPA 2023), you have the right to:</p>
            <ul>
              <li><strong>Access:</strong> Request a copy of your personal data</li>
              <li><strong>Correction:</strong> Update or correct your personal information</li>
              <li><strong>Deletion:</strong> Request deletion of your account and associated data</li>
              <li><strong>Portability:</strong> Export your measurement data</li>
              <li><strong>Withdraw Consent:</strong> Opt out of data processing at any time</li>
            </ul>
            <p>To exercise these rights, contact us at <a href="mailto:aibodyscan123@gmail.com" className="text-accent-400 hover:text-accent-300">aibodyscan123@gmail.com</a>.</p>
          </Section>

          <Section title="8. Cookies & Local Storage">
            <p>We use cookies and local storage for authentication tokens, user preferences (dark mode, measurement units), and caching. You can manage cookie preferences through our cookie consent banner.</p>
          </Section>

          <Section title="9. Children's Privacy">
            <p>Our Service is not intended for users under 16 years of age. We do not knowingly collect information from children.</p>
          </Section>

          <Section title="10. Changes to This Policy">
            <p>We may update this Privacy Policy from time to time. We will notify you of material changes via email or in-app notification.</p>
          </Section>

          <Section title="11. Contact Us">
            <p>For privacy-related questions or concerns:</p>
            <ul>
              <li>Email: <a href="mailto:aibodyscan123@gmail.com" className="text-accent-400 hover:text-accent-300">aibodyscan123@gmail.com</a></li>
              <li>App: Profile → Contact Us</li>
            </ul>
          </Section>
        </div>
      </motion.div>
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="bg-slate-900/80 backdrop-blur-xl rounded-2xl border border-slate-700/60 p-6">
    <h3 className="text-lg font-bold text-white mb-4">{title}</h3>
    <div className="text-slate-300 text-sm leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_li]:text-slate-400">
      {children}
    </div>
  </div>
);

export default PrivacyPolicyPage;
